<a href="https://colab.research.google.com/github/Willymwa85/Great-Britain-Political-Data-Analysis-with-Tableau/blob/main/Copy_of_01_tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for 'jovian.commit' to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1LsqAAbxfY4AP0bty3md-7-VPdG5IhMTG')

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 kB 934.9 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done


> ### Assignment Instructions (delete this cell before submission)
>
> The objective of this assignment is to develop a solid understanding of PyTorch tensors. In this assignment you will:
>
> 1. Pick 5 interesting functions related to PyTorch tensors by [reading the documentation](https://pytorch.org/docs/stable/torch.html),
> 2. Edit this starter template notebook to illustrate their usage and publish your notebook to Jovian using `jovian.commit`. Make sure to add proper explanations too, not just code.
> 3. Submit the link to your published notebook on Jovian here: https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor .
> 4. (Optional) Write a blog post on [Medium](https://medium.com) to accompany and showcase your Jupyter notebook. [Embed cells from your notebook](https://medium.com/@aakashns/share-and-embed-jupyter-notebooks-online-with-jovian-ml-df709a03064e) wherever necessary.
> 5. (Optional) [Share your work](https://jovian.ai/forum/t/pytorch-functions-and-tensor-operations/13790) with the community and exchange feedback with other participants
>
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Colab". Run `jovian.commit` regularly to save your progress.
>
> Try to give your notebook an interesting title e.g. "All about PyTorch tensor operations", "5 PyTorch functions you didn't know you needed", "A beginner's guide to Autograd in PyToch", "Interesting ways to create PyTorch tensors", "Trigonometic functions in PyTorch", "How to use PyTorch tensors for Linear Algebra" etc.
>
> **IMPORTANT NOTE**: Make sure to submit a Jovian notebook link e.g. https://jovian.ai/aakashns/01-tensor-operations . Colab links will not be accepted.
>
> Remove this cell containing instructions before making a submission or sharing your notebook, to make it more presentable.
>



# Title Here
Introduction
PyTorch is an open source machine learning library based on Python and developed by Facebook's AI research group. It is used for applications such as computer vision and natural language processing.

Some key features of PyTorch:

- Provides tensors and dynamic neural networks with strong GPU acceleration. Tensors are similar to NumPy arrays but can also be run on GPUs.
- Has an autograd system that automatically calculates gradients required for backpropagation in neural networks. This makes PyTorch a useful tool for deep learning research.
- Supports neural network modules like convolution layers, recurrent layers, and linear layers. These can be used to build and train deep neural networks.
- Integrates well with Python data science stacks like NumPy, SciPy and matplotlib.
- Can be used for rapid prototyping and experimentation as model architectures can be defined and tweaked dynamically.
- Has high performance distributed training capabilities via integration with libraries like Horovod.
- Supported by companies like Facebook, Twitter and Nvidia. Has an active open source community contributing to it.

In summary, PyTorch is a Python-based framework designed for building and training deep neural networks. Its key advantages are ease of use, flexibility, and speed, making it a popular choice for academics, researchers and companies to implement deep learning algorithms.

The below 5 functions are the chosen functions for discussion.

- torch.zeros_like
- torch.normal
- torch.hstack
- torch.sqrt
- torch.gather

Before we begin, let's install and import PyTorch

In [ ]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [ ]:
# Import torch and other required modules
import torch

## Function 1 - torch.zeros_like
- torch.zeros_like(input, dtype=None, layout=None, device=None, requires_grad=False)
- Creates a tensor of zeros with the same size as the input tensor.
- Usage: Initialize a tensor to zero for numeric stability in some models.


In [ ]:
# Example 1 - working
x = torch.rand(2, 3)
y = torch.zeros_like(x) # y is 2x3 tensor of zeros
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


Explanation about example

In [ ]:
# Example 2 - working
w = torch.empty(4, 4)
b = torch.zeros_like(w, requires_grad=True) # b requires grad
print(b)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], requires_grad=True)


Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
z = 'string'
torch.zeros_like(z) # Error, input must be tensor

TypeError: zeros_like(): argument 'input' (position 1) must be Tensor, not str

Explanation about example

Closing comments about when to use this function

Let's save our work using Jovian before continuing.

In [ ]:
!pip install jovian --upgrade --quiet

In [ ]:
import jovian

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...


ApiError: Colab commit failed: (HTTP 404) No file found for the provided File ID

## Function 2 - torch.normal
- torch.normal(mean, std, size)
- Creates a tensor with values sampled from the normal distribution.
- Usage: Initialize weights in some neural network layers.



In [ ]:
# Example 1 - working
x = torch.normal(0, 1, size=(3,3)) # Normal distribution
print(x)

tensor([[-1.1048, -0.7207,  0.1671],
        [ 1.0507, -0.7193, -1.8015],
        [-1.1537,  0.4862, -0.3306]])


Explanation about example

In [ ]:
# Example 2 - working
y = torch.normal(0, 0.1, size=(5,)) # Small std dev
print(y)

tensor([ 0.0324,  0.0251,  0.1475, -0.0635,  0.0407])


Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
z = torch.normal(0, 1) # Error, missing size

TypeError: normal() received an invalid combination of arguments - got (int, int), but expected one of:
 * (Tensor mean, Tensor std, *, torch.Generator generator, Tensor out)
 * (Tensor mean, float std, *, torch.Generator generator, Tensor out)
 * (float mean, Tensor std, *, torch.Generator generator, Tensor out)
 * (float mean, float std, tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


Explanation about example

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...


ApiError: Colab commit failed: (HTTP 404) No file found for the provided File ID

## Function 3 - torch.hstack
- torch.hstack(tensors)
- Stacks tensors horizontally.
- Usage: Concatenate tensors along a new horizontal axis.



In [ ]:
# Example 1 - working
x = torch.randn(2, 3)
y = torch.randn(2, 2)
z = torch.hstack([x, y]) # z is 2x5
print(z)

tensor([[ 0.5646, -0.0486,  1.0423,  1.7152, -1.4634],
        [ 0.3076,  1.5276, -0.9129,  0.5699, -0.3216]])


Explanation about example

In [ ]:
# Example 2 - working
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
torch.hstack([a,b]) # [1,2,3,4,5,6]

tensor([1, 2, 3, 4, 5, 6])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
p = torch.tensor([1,2])
torch.hstack(p) # Error, expected list of tensors

TypeError: hstack(): argument 'tensors' (position 1) must be tuple of Tensors, not Tensor

Explanation about example

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...


ApiError: Colab commit failed: (HTTP 404) No file found for the provided File ID

## Function 4 - torch.sqrt
- torch.sqrt(input)
- Computes the square root of each element of the input tensor.
- Usage: Useful for normalization and scaling.



In [ ]:
# Example 1 - working
x = torch.tensor([4, 9, 16])
torch.sqrt(x) # [2, 3, 4]

tensor([2., 3., 4.])

Explanation about example

In [ ]:
# Example 2 - working
y = torch.rand(2,3)
torch.sqrt(y) # Square root of each element

tensor([[0.7782, 0.7102, 0.6912],
        [0.7969, 0.1461, 0.8536]])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
z = 'string'
torch.sqrt(z) # Error, expected tensor input

TypeError: sqrt(): argument 'input' (position 1) must be Tensor, not str

Explanation about example

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...


ApiError: Colab commit failed: (HTTP 404) No file found for the provided File ID

## Function 5 - torch.gather
- torch.gather(input, dim, index)
- Gathers values along an axis specified by dim.
- Usage: Select/filter out elements based on index.



In [ ]:
# Example 1 - working
x = torch.tensor([[1,2],[3,4]])
torch.gather(x, 1, torch.tensor([[0,0],[1,0]])) # [[1,1],[4,3]]

tensor([[1, 1],
        [4, 3]])

Explanation about example

In [ ]:
# Example 2 - working
y = torch.rand(3,4)
idx = torch.tensor([[0], [1]]) # idx is now 2D

torch.gather(y, 0, idx)

tensor([[0.7386],
        [0.7208]])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
z = torch.gather(x, 2, idx) # Error, dim 2 does not exist

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

Explanation about example

Closing comments about when to use this function

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...


ApiError: Colab commit failed: (HTTP 404) No file found for the provided File ID

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [ ]:
jovian.commit(project='01-tensor-operations')